# Generated by Django 4.1.3 on 2023-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsDomainLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_id", models.IntegerField()),
                ("domain_name", models.CharField(max_length=255)),
                ("site_id", models.IntegerField()),
                ("site_name", models.CharField(max_length=255)),
                ("domain_url", models.TextField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("site_name_bn", models.CharField(max_length=255)),
                ("is_bengali", models.BooleanField()),
                ("is_english", models.BooleanField()),
                ("site_url", models.TextField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
