# Generated by Django 4.1.3 on 2023-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("news_preference", models.TextField(max_length=1000)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="added at"),
                ),
            ],
        ),
    ]
